stages:
  train_yolo:
    cmd: python -m src.training.train_yolo
    deps:
      - src/training/train_yolo.py
      - Data/processed/yolo_fracture/dataset.yaml
    outs:
      - experiments/yolo_results/medical_fracture_v1/weights/best.pt

  train_mls:
    cmd: python -m src.training.train_mls
    deps:
      - src/training/train_mls.py
      - Data/metadata/training_df.csv
      - src/training/mls_models.py
    outs:
      - models/checkpoints/slice_selector_best.ckpt
      - models/checkpoints/keypoint_best.ckpt

  train_nnunet:
    cmd: python -m src.training.train_nnunet
    deps:
      - src/training/train_nnunet.py
      - Data/processed/nnUNet/nnUNet_raw
    # چون خروجی nnU-Net اسمش متغیر است، فعلا کل پوشه خروجی را مانیتور می‌کنیم
    outs:
      - Data/processed/nnUNet/nnUNet_results