"""Evaluate a frozen conservative three-fold MLS OOF recipe.

This program never loads a model or an image.  It combines full-study slice
predictions that were already generated by CUDA audits, applies one fixed
pooling profile, and reports aggregate OOF metrics without serialising
study-level predictions.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np

from screen_mls_crossrun_component_blends import (
    PROFILES,
    _candidate_payloads,
    _load,
    _validate_alignment,
)
from search_mls_crossfold_pooling import _metrics, _predict


ABS_TOLERANCE = 1e-9


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def _metric_payload(truth: np.ndarray, prediction: np.ndarray) -> dict[str, float]:
    raw = _metrics(truth, prediction)
    boundary_f1 = float(np.mean([raw["f1_3mm"], raw["f1_5mm"]]))
    return {
        "mae_mm": float(raw["mae_mm"]),
        "rmse_mm": float(raw["rmse_mm"]),
        "bias_mm": float(raw["bias_mm"]),
        "f1_3mm": float(raw["f1_3mm"]),
        "f1_5mm": float(raw["f1_5mm"]),
        "boundary_f1": boundary_f1,
        "selection_objective": float(raw["mae_mm"] + 2.0 * (1.0 - boundary_f1)),
    }


def _assert_close(label: str, actual: float, expected: float) -> None:
    if not np.isclose(actual, expected, rtol=0.0, atol=ABS_TOLERANCE):
        raise RuntimeError(
            f"Parity failed for {label}: actual={actual}, expected={expected}, "
            f"tolerance={ABS_TOLERANCE}"
        )


def _deltas(candidate: dict[str, float], baseline: dict[str, float]) -> dict[str, float]:
    return {key: float(candidate[key] - baseline[key]) for key in baseline}


def _bootstrap(
    truth: np.ndarray,
    baseline: np.ndarray,
    candidate: np.ndarray,
    *,
    seed: int,
    replicates: int,
) -> dict[str, Any]:
    rng = np.random.default_rng(seed)
    names = ("mae_mm", "boundary_f1", "selection_objective")
    values = {name: np.empty(replicates, dtype=np.float64) for name in names}
    for replicate in range(replicates):
        indices = rng.integers(0, len(truth), size=len(truth))
        baseline_metrics = _metric_payload(truth[indices], baseline[indices])
        candidate_metrics = _metric_payload(truth[indices], candidate[indices])
        for name in names:
            values[name][replicate] = candidate_metrics[name] - baseline_metrics[name]
    payload: dict[str, Any] = {
        "design": "paired_study_bootstrap",
        "seed": seed,
        "replicates": replicates,
        "interval": "percentile_95pct",
        "delta_definition": "candidate_minus_baseline",
        "metrics": {},
    }
    for name, samples in values.items():
        lower, upper = np.quantile(samples, [0.025, 0.975])
        improving = samples >= 0.0 if name == "boundary_f1" else samples <= 0.0
        payload["metrics"][name] = {
            "lower": float(lower),
            "median": float(np.median(samples)),
            "upper": float(upper),
            "probability_improving": float(np.mean(improving)),
        }
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    if spec.get("schema_version") != 1:
        raise ValueError("Unsupported spec schema_version")
    profile = PROFILES[spec["profile"]]
    all_study_ids: set[str] = set()
    truth_parts: list[np.ndarray] = []
    baseline_parts: list[np.ndarray] = []
    candidate_parts: list[np.ndarray] = []
    fold_results: list[dict[str, Any]] = []
    input_hashes: list[dict[str, Any]] = []

    for fold_spec in spec["folds"]:
        fold = int(fold_spec["fold"])
        expected_studies = int(fold_spec["expected_studies"])
        baseline_path = args.repo_root / fold_spec["baseline"]
        baseline_frame, baseline_payloads = _load(baseline_path, expected_studies)
        study_ids = set(baseline_frame["study_id"].astype(str))
        overlap = sorted(study_ids & all_study_ids)
        if overlap:
            raise RuntimeError(f"OOF study overlap at fold {fold}: {overlap[:3]}")
        all_study_ids.update(study_ids)

        candidate_payloads = baseline_payloads
        challenger_path: Path | None = None
        if fold_spec.get("challenger"):
            challenger_path = args.repo_root / fold_spec["challenger"]
            challenger_frame, challenger_payloads = _load(
                challenger_path, expected_studies
            )
            _validate_alignment(
                baseline_frame,
                baseline_payloads,
                challenger_frame,
                challenger_payloads,
                str(fold_spec["challenger_label"]),
            )
            candidate_payloads = _candidate_payloads(
                baseline_payloads,
                challenger_payloads,
                float(fold_spec["alpha"]),
                str(fold_spec["component_mode"]),
            )

        truth = baseline_frame["gt_MLS_mm"].to_numpy(float)
        baseline_prediction = np.asarray(
            [_predict(items, profile) for items in baseline_payloads], dtype=float
        )
        candidate_prediction = np.asarray(
            [_predict(items, profile) for items in candidate_payloads], dtype=float
        )
        baseline_metrics = _metric_payload(truth, baseline_prediction)
        candidate_metrics = _metric_payload(truth, candidate_prediction)
        for metric in ("mae_mm", "boundary_f1", "selection_objective"):
            _assert_close(
                f"fold{fold}.baseline.{metric}",
                baseline_metrics[metric],
                float(fold_spec["expected_baseline"][metric]),
            )
            _assert_close(
                f"fold{fold}.candidate.{metric}",
                candidate_metrics[metric],
                float(fold_spec["expected_candidate"][metric]),
            )

        fold_results.append(
            {
                "fold": fold,
                "expected_studies": expected_studies,
                "baseline_label": fold_spec["baseline_label"],
                "challenger_label": fold_spec.get("challenger_label"),
                "component_mode": fold_spec.get("component_mode", "baseline_only"),
                "challenger_alpha": float(fold_spec.get("alpha", 0.0)),
                "baseline": baseline_metrics,
                "candidate": candidate_metrics,
                "delta": _deltas(candidate_metrics, baseline_metrics),
            }
        )
        input_hashes.append(
            {
                "fold": fold,
                "role": "baseline",
                "path": str(baseline_path),
                "sha256": _sha256(baseline_path),
            }
        )
        if challenger_path is not None:
            input_hashes.append(
                {
                    "fold": fold,
                    "role": "challenger",
                    "path": str(challenger_path),
                    "sha256": _sha256(challenger_path),
                }
            )
        truth_parts.append(truth)
        baseline_parts.append(baseline_prediction)
        candidate_parts.append(candidate_prediction)

    truth_all = np.concatenate(truth_parts)
    baseline_all = np.concatenate(baseline_parts)
    candidate_all = np.concatenate(candidate_parts)
    baseline_oof = _metric_payload(truth_all, baseline_all)
    candidate_oof = _metric_payload(truth_all, candidate_all)
    delta_oof = _deltas(candidate_oof, baseline_oof)
    gates = spec["release_gates"]
    gate_results = {
        "mae_noninferior": bool(delta_oof["mae_mm"] <= ABS_TOLERANCE),
        "boundary_f1_noninferior": bool(
            delta_oof["boundary_f1"] >= -ABS_TOLERANCE
        ),
        "objective_improvement": bool(
            delta_oof["selection_objective"]
            <= -float(gates["minimum_objective_improvement"]) + ABS_TOLERANCE
        ),
    }
    passed = bool(all(gate_results.values()))
    macro = {}
    for role in ("baseline", "candidate"):
        macro[role] = {
            metric: float(np.mean([row[role][metric] for row in fold_results]))
            for metric in ("mae_mm", "boundary_f1", "selection_objective")
        }
    macro["delta"] = _deltas(macro["candidate"], macro["baseline"])
    bootstrap = _bootstrap(
        truth_all,
        baseline_all,
        candidate_all,
        seed=int(spec["bootstrap_seed"]),
        replicates=int(spec["bootstrap_replicates"]),
    )
    payload = {
        "schema_version": 1,
        "evaluation_design": "frozen_conservative_threefold_oof",
        "compute_policy": "saved_cuda_predictions_cpu_postprocessing_only",
        "warning": (
            "No model or image inference was run. Study-level prediction payloads "
            "remain excluded from this aggregate artifact."
        ),
        "spec_path": str(args.spec),
        "spec_sha256": _sha256(args.spec),
        "profile": spec["profile"],
        "n_folds": len(fold_results),
        "n_unique_oof_studies": len(all_study_ids),
        "inputs": input_hashes,
        "folds": fold_results,
        "micro_oof": {
            "baseline": baseline_oof,
            "candidate": candidate_oof,
            "delta": delta_oof,
        },
        "macro_fold": macro,
        "release_gates": gates,
        "gate_results": gate_results,
        "passed": passed,
        "bootstrap": bootstrap,
        "decision": (
            "Conservative three-fold OOF candidate passed the frozen aggregate gates."
            if passed
            else "Conservative three-fold OOF candidate failed the frozen aggregate gates."
        ),
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    _atomic_text(
        args.output_dir / "conservative_threefold_oof_summary.json",
        json.dumps(payload, indent=2) + "\n",
    )
    lines = [
        "# Conservative three-fold MLS OOF result",
        "",
        f"- Studies: `{payload['n_unique_oof_studies']}` across `{payload['n_folds']}` held-out folds",
        f"- Baseline micro MAE: `{baseline_oof['mae_mm']:.9f}`",
        f"- Candidate micro MAE: `{candidate_oof['mae_mm']:.9f}`",
        f"- MAE delta: `{delta_oof['mae_mm']:+.9f}`",
        f"- Baseline micro Boundary-F1: `{baseline_oof['boundary_f1']:.9f}`",
        f"- Candidate micro Boundary-F1: `{candidate_oof['boundary_f1']:.9f}`",
        f"- Boundary-F1 delta: `{delta_oof['boundary_f1']:+.9f}`",
        f"- Baseline micro objective: `{baseline_oof['selection_objective']:.9f}`",
        f"- Candidate micro objective: `{candidate_oof['selection_objective']:.9f}`",
        f"- Objective delta: `{delta_oof['selection_objective']:+.9f}`",
        f"- Decision: {payload['decision']}",
        "",
        payload["warning"],
    ]
    _atomic_text(
        args.output_dir / "CONSERVATIVE_THREEFOLD_OOF_REPORT.md",
        "\n".join(lines) + "\n",
    )
    print(json.dumps(payload, indent=2))
    return 0 if passed else 2


if __name__ == "__main__":
    raise SystemExit(main())
